apiVersion: v2
name: cert-manager-wrapper
description: Wrapper chart to install cert-manager via Helm
type: application
version: 0.1.0

dependencies:
  - name: cert-manager
    version: "v1.20.1"
    repository: https://charts.jetstack.io
